version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: demo:app
    ports:
      - 80:80
    volumes:
      - ./:/app
    command: "streamlit run app/main.py"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    runtime: nvidia
    image: demo:api
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    command: "python api/main.py"
