version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    image: demo:app
    ports:
      - 80:80
    volumes:
      - ./:/app
    command: "streamlit run app/main.py"
